#!/usr/bin/perl
#
# right-clicking on a filename in what looks like an `ls -l` listing will
# paste the escaped value of that filename
#
# Copyright (c) 2024 joshua stein <jcs@jcs.org>
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#

sub on_button_press {
	my ($self, $event) = @_;

	if ($event->{button} == 3) {
		my $line = $self->line($event->{row});
		my $off = $line->offset_of($event->{row}, $event->{col});

		if ($line->t =~ /^[d-]......... .+? [A-Z][a-z][a-z] [\d ]\d (\d\d:\d\d| \d\d\d\d) (.+)/) {
			if ($-[2] <= $off && $+[2] >= $off) {
				$self->{term}->tt_write(quotemeta($2));
			}
		}

		return 1;
	}

	()
}
